### ISSUE TITLE
Droits sur le dépôt

### ISSUE THREAD

**Issue by NicolasGlassey** [Sylvain-Lechaire/projetWeb#2]
@Sylvain-Lechaire 

Pourriez-vous me donner les droits en écriture sur le dépôt.

Onglet [Setting/Collaborate] et ajouter mon email cpnv.ch

**Comment by Sylvain-Lechaire** [comment]
je vous ais invité a rejoindre le dépôt, cela devrais jouer si je me suis pas planté.

**Comment by NicolasGlassey** [comment]
C'est tout bon !
